base_url = "https://pursuit-of-simplicity.pages.dev"

compile_sass = false
minify_html = true

build_search_index = true

theme = "anemone"

taxonomies = [{ name = "tags", feed = true }]

generate_feeds = true

[markdown]
highlight_code = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
default_theme = "dark"

author = "Benjamin"
display_author = true

list_pages = false

header_nav = [
  { url = "/", name_en = "/home/" },
  { url = "/blog", name_en = "/blog/" },
]
